### ISSUE TITLE
Antenna to be used with HackRF

### ISSUE THREAD

**Issue by Rohan131293** [lucasduffey/LTE-Cell-Scanner#15]
Hello,
In order to cover LTE 800 and 2600 with same antenna using HackRF ,what is the best choice?Which antenna you have used while working with HackRF in this band.What parameters other than frequency to be considered while deciding antenna?The default antenna with HackRF is ANT500 which supports till 1.1GHz only.Is it totally useless above this limit?
Thanks....

**Comment by lucasduffey** [comment]
You might be able to use any antenna meant for 2.4 GHz wifi if you have some

quick search on amazon for possible option (haven't personally used it):
https://www.amazon.com/TECHTOO-700-2600Mhz-Directional-Connector-Wireless/dp/B00U7QAFAW/ref=sr_1_11?ie=UTF8&qid=1490896665&sr=8-11&keywords=Antenna+LTE
